server.port=8084
spring.application.name=kpi-service

# Base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/cordillera_kpi?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Data Service
services.data.url=http://localhost:8083

# Logging
logging.level.cl.duoc.cordillera=DEBUG